import Head from 'next/head';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import HomeComponent from '@/components/pages/Home.component';
import useColor from '@/hooks/useColor';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { colors } = useColor();
  return (
    <>
      <Head>
        <title>Juan Daniel | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`${styles.main} main`}
        style={{
          background: `linear-gradient(145deg, ${colors.secondary}, ${colors.dark} )`,
        }}
      >
        <HomeComponent />
      </main>
    </>
  );
}
